### ISSUE TITLE
Cant change sensor unit of measurement.

### ISSUE THREAD

**Issue by obbers** [BHSPitMonkey/homeassistant-garmin-mapshare#3]
Currently, units of measurement are in metric.  There's a configuration option missing to allow switching between different measurement types.  Please see https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors

I'm using 2023.12.4.

**Comment by BHSPitMonkey** [comment]
Fixed in v0.3.0!
