### ISSUE TITLE
Support for multiple devices

### ISSUE THREAD

**Issue by shiftylilbastrd** [BHSPitMonkey/homeassistant-garmin-mapshare#6]
Thanks for this. You have any idea when multi device support will be available? I currently have two devices and of course my secondary device is the one that populates in HA.

**Comment by BHSPitMonkey** [comment]
That's odd; Multiple devices under the same MapShare URL _should_ all populate in Home Assistant. 


Can you download the KML data from `https://share.garmin.com/Feed/Share/YOUR_NAME` and check whether both devices seem to be represented there? If they are, feel free to redact names/etc. from that KML and either share it here or send it to the email in my git commits and I'll take a look when I can.

**Comment by shiftylilbastrd** [comment]
My 66i is in there but my Mini 2 isn't.

**Comment by shiftylilbastrd** [comment]
You can disregard and close this. I hadn't used my new device for tracking yet, it was active but not sending track points. I sent one and refreshed the integration and it showed up.
