### ISSUE TITLE
 Unexpected error, when setting up the integration

### ISSUE THREAD

**Issue by karba78** [BHSPitMonkey/homeassistant-garmin-mapshare#7]
Hello
thank you for your code
installed the integration without issue
when setting it up with my shared url I systematically get the "unexpected error" message
tried with and without password ( on Garmin shared page parameter) does not change anything
thank you

This error originated from a custom integration.

Logger: custom_components.garmin_mapshare.config_flow
Source: custom_components/garmin_mapshare/config_flow.py:63
integration: Garmin MapShare (documentation, issues)
First occurred: 10:11:20 AM (5 occurrences)
Last logged: 10:14:43 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/garmin_mapshare/config_flow.py", line 63, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_mapshare/config_flow.py", line 41, in validate_input
    if not await hub.authenticate():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_mapshare/kml_fetch.py", line 57, in authenticate
    devices = await self.fetch_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garmin_mapshare/kml_fetch.py", line 93, in fetch_data
    r.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://share.garmin.com/Feed/Share/https://share.garmin.com/share/xxxxxx'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

**Comment by karba78** [comment]
solved, had to put only the last part (name) in the parameter, not the full url
this

**Comment by hajosc** [comment]
+1 - updating the documentation would probably be in order

**Comment by BHSPitMonkey** [comment]
I've just published a new release (v1.2.0) with a change making it so that the full URL will also be accepted (5f18c389900d6bde967a041d1e6450a6bd0f0813). Hope this makes future installs a little easier!
