### ISSUE TITLE
Last Updated unusable 

### ISSUE THREAD

**Issue by gibeautc** [BHSPitMonkey/homeassistant-garmin-mapshare#8]
Maybe I am missing something, but I see in the devices attributes, there is a "last updated" field, which shows the timestamp. 
But I am not able to find anyway to use that attribute in an automation, ie "If Device.lastUpdated is older then 6 hours then do something" 

Should that be possible, or is that field purely informational with no ability to act on it.

**Comment by BHSPitMonkey** [comment]
I think this is more of a general Home Assistant question than a question about this particular integration, so I'd encourage you to seek guidance from the community of experts there; I don't know the exact best way to do this, but you will probably want to set up a Template helper with something similar to the examples given in [this forum post](https://community.home-assistant.io/t/run-automation-if-input-datetime-sensor-is-older-than-5-days/679086/2). (And then, you can automate based on the state of that helper entity changing.)

**Comment by gibeautc** [comment]
Sounds good, Thanks for the info even though it was outside the scope of the integration
